In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression(max_iter=1000)
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9481481481481482

In [4]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9833333333333333

In [5]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9611111111111111

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def gs(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [9]:
gs(SVC(),x_train,x_test,y_train,y_test)

0.9833333333333333

In [24]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits = 3)

In [50]:
slog = []
ssvm = []
srandfor = []

for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    slog.append(gs(LogisticRegression(max_iter = 1000),x_train,x_test,y_train,y_test))
    ssvm.append(gs(SVC(),x_train,x_test,y_train,y_test))
    srandfor.append(gs(RandomForestClassifier(n_estimators = 40),x_train,x_test,y_train,y_test))
print(slog)
print(ssvm)
print(srandfor)

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]
[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
[0.9398998330550918, 0.9549248747913188, 0.9165275459098498]


In [52]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [54]:
#we can use this instead of doing the full appending stages

In [ ]:
avg_log = sum(slog)//len(slog)
avg_svm = sum(ssvm)//len(ssvm)
avg_rf = sum(srandfor)//len(srandfor)
x = [avg_log,avg_svm,avg_rf]
mx = max(x)
if mx == avg_svm:
    print("SVM goat")
elif mx == avg_log:
    print("Logistic regression goat")
elif 